# Generated by Django 4.1.5 on 2023-05-18 08:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0007_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="mobile",
            field=models.TextField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.CreateModel(
            name="AccountLevelShippingInfo",
            fields=[
                ("address_title", models.CharField(default="Untitled", max_length=25)),
                (
                    "address_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_default_address", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("landmark", models.CharField(blank=True, max_length=200, null=True)),
                ("postalCode", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("lastModified", models.DateTimeField(auto_now=True)),
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
