# Generated by Django 4.1.5 on 2023-05-18 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_account_mobile_accountlevelshippinginfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
