# Generated by Django 4.1.5 on 2023-05-18 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_account_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.RegexValidator("[0-9]$"),
                ],
            ),
        ),
    ]
