# Generated by Django 4.1.5 on 2023-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_account_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="review_image",
            field=models.ImageField(blank=True, null=True, upload_to="Review_Images"),
        ),
    ]
