# Generated by Django 4.1.5 on 2023-05-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlevelshippinginfo",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOME", "HOME"),
                    ("APARTMENT", "APARTMENT"),
                    ("OFFICE", "OFFICE"),
                    ("OTHER", "OTHER"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
