# Generated by Django 4.1.5 on 2023-05-18 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_wishlist_wtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="isPurchased",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.CreateModel(
            name="WishListItems",
            fields=[
                ("isPurchased", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.product",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.wishlist"
                    ),
                ),
            ],
        ),
    ]
