# Generated by Django 4.1.5 on 2023-05-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_wishlist_ispurchased_remove_wishlist_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountlevelshippinginfo",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[("FL", "8am to 10 pm"), ("WH", "10am to 6 pm")],
                max_length=10,
                null=True,
            ),
        ),
    ]
