# Generated by Django 4.1.5 on 2023-05-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_accountlevelshippinginfo_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="lastmodified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
