# Generated by Django 4.1.5 on 2023-05-23 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0017_account_lastmodified"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLevelShippingInfo2",
            fields=[
                ("address_title", models.CharField(default="Untitled", max_length=25)),
                (
                    "address_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOME", "HOME"),
                            ("APARTMENT", "APARTMENT"),
                            ("OFFICE", "OFFICE"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_default_address", models.BooleanField(default=False)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[("FL", "8am to 10 pm"), ("WH", "10am to 6 pm")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("landmark", models.CharField(blank=True, max_length=200, null=True)),
                ("postalCode", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("lastModified", models.DateTimeField(auto_now=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
