# Generated by Django 4.1.5 on 2023-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_shippinglist_remove_accountlevelshippinginfo2_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippinglist",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[("FULL", "8am to 10 pm"), ("HALF", "10am to 6 pm")],
                max_length=10,
                null=True,
            ),
        ),
    ]
