# Generated by Django 4.1.5 on 2023-05-25 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_remove_order_status_order_ostatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_video",
            field=models.FileField(
                null=True,
                upload_to="Review_Images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
