# Generated by Django 4.1.5 on 2023-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_review_review_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="lastmodified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
