# Generated by Django 4.1.5 on 2023-05-25 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_review_lastmodified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="Review_Images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
    ]
